# Generated by Django 5.1.1 on 2024-09-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('history', models.CharField(max_length=1000)),
                ('personality', models.CharField(max_length=1000)),
                ('physical_description', models.CharField(max_length=1000)),
                ('skills', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.UUIDField()),
                ('theme', models.CharField(max_length=100)),
                ('starting_details', models.CharField(max_length=1000)),
                ('characters', models.ManyToManyField(to='games.character')),
                ('locations', models.ManyToManyField(to='games.location')),
                ('skills', models.ManyToManyField(to='games.skill')),
            ],
        ),
    ]
