# Generated by Django 5.1.1 on 2024-09-04 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='access_key',
            new_name='save_key',
        ),
    ]
