# Generated by Django 5.1.1 on 2024-09-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_character_created_character_modified_game_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='total_dollar_cost',
        ),
        migrations.AddField(
            model_name='game',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
