# Generated by Django 5.1.1 on 2024-09-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_timeframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='history',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='personality',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='physical_description',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='starting_details',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='theme',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeframe',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
