# Generated by Django 5.1.1 on 2024-09-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_character_history_alter_character_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='total_dollar_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
