# Generated by Django 5.1.1 on 2024-09-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_total_dollar_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turns',
            field=models.IntegerField(default=0),
        ),
    ]
